AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.

Parameters:
  githubrepo:
    Type: String
    Description: The GitHub profile to scan (i.e. 'marekq' for https://github.com/marekq)
    Default: marekq

Resources:
  sqsqueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60

  gitpulllayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: gitlayer
      Description: create a layer with gitpull tools
      ContentUri: layer/.
      CompatibleRuntimes:
        - python3.8
      LicenseInfo: MIT
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.8

  gitpull:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:553035198032:layer:git-lambda2:6
        - !Ref gitpulllayer
      Runtime: python3.8
      Handler: lambda.handler
      CodeUri: lambda/
      Tracing: Active
      Description: 'Retrieve GitHub repositories, scan them  feeds and store them in DynamoDB'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref gittable
      MemorySize: 1024
      Timeout: 20
      Events:
        sqstrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt sqsqueue.Arn
            BatchSize: 1
      ReservedConcurrentExecutions: 10

  discoverrepo:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 256
      Timeout: 30
      CodeUri: startscan/
      Handler: startscan.handler
      Runtime: python3.8
      Tracing: Active
      ReservedConcurrentExecutions: 1
      Layers:
        - !Ref gitpulllayer
      Environment:
        Variables:
          sqsqueue: !Ref sqsqueue
          githubrepo: !Ref githubrepo
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt sqsqueue.QueueName

  gittable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: gitrepo
        AttributeType: S
      - AttributeName: timest
        AttributeType: S
      KeySchema:
      - AttributeName: gitrepo
        KeyType: HASH
      - AttributeName: timest
        KeyType: RANGE  
      BillingMode: PAY_PER_REQUEST
