AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Scan GitHub repositories with cfn-lint and store the results in DynamoDB

Parameters:
  githubrepo:
    Type: String
    Description: The GitHub profile to scan (i.e. 'marekq' for https://github.com/marekq)
    Default: marekq

Resources:
  sqsqueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60

  gitpulllayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: gitlayer
      Description: create a layer with gitpull tools
      ContentUri: layer/.
      CompatibleRuntimes:
        - python3.8
      LicenseInfo: MIT
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.8

  gitpull:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Ref gitpulllayer
      Runtime: python3.8
      Handler: lambda.handler
      CodeUri: lambda/
      Tracing: Active
      Description: 'Scan Github repositories and store results in DynamoDB'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref gittable
      MemorySize: 1536
      Timeout: 30
      Events:
        sqstrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt sqsqueue.Arn
            BatchSize: 1
      ReservedConcurrentExecutions: 10
      Environment: 
        Variables:
          dynamo_table: !Ref gittable
        
  discoverrepo:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 256
      Timeout: 30
      CodeUri: startscan/
      Handler: startscan.handler
      Runtime: python3.8
      Tracing: Active
      Description: 'Get a list Github repositories and submit them to SQS'
      ReservedConcurrentExecutions: 1
      Layers:
        - !Ref gitpulllayer
      Environment:
        Variables:
          sqsqueue: !Ref sqsqueue
          githubrepo: !Ref githubrepo
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt sqsqueue.QueueName

  gittable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: gitrepo
        AttributeType: S
      - AttributeName: check_id
        AttributeType: S
      - AttributeName: srcuuid
        AttributeType: S
      KeySchema:
      - AttributeName: gitrepo
        KeyType: HASH
      - AttributeName: check_id
        KeyType: RANGE  
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
      - IndexName: scanguid
        KeySchema:
        - AttributeName: srcuuid
          KeyType: HASH
        - AttributeName: gitrepo
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
